### ISSUE TITLE
Subscription Topic does not handle equipment names with slashes in them.

### ISSUE THREAD

**Issue by geoff-nunan** [Spruik/libre-common#3]
When the historian service subscribes to MQTT topics, it produces the following subscriptions:
+/EdgeEvent/#
+/EdgeTagChange/#

When the Equipment names have slashes in them like CLT/MFG/packml-sim-0 the historian does not pick up the massages because the subscription needs to be +/+/+/EdgeEvent/#

An alternative solution may be to use a flat structure for "edgeToCentral" message publishing rather than using the equipment name. Use the EquimentId instead perhaps? You loose the human readability of the topic names, but keep the code simple.

The topic structure suggested in confluence here https://libremfg.atlassian.net/wiki/spaces/LC/pages/286163286/Topic+Structure
might help

https://github.com/Spruik/libre-common/blob/eceae7d47a811285e2d6146ae609af420e0dda4a/common/drivers/edgeConnectorMQTT.go#L184

**Comment by bruchte** [comment]
committed changes to historian to correct this.  Added the use a EquipmentFinder to tailor the equipment that is referenced.  With the found equipment, the correct subscription strings are build based on how many levels are in the name (eq=A/B give subscription +/+, eq=A/B/C/D gives +/+/+/+
